### ISSUE TITLE
compiled version.

### ISSUE THREAD

**Issue by ghost** [noptrix/lulzbuster#1]
Hi. Is there any chance to somehow obtain compiled executable version? I can't build it on my windows machine. Sorry if github issues if not for such a stuff, i don't know where else i can ask

**Comment by noptrix** [comment]
> Hi. Is there any chance to somehow obtain compiled executable version? I can't build it on my windows machine. Sorry if github issues if not for such a stuff, i don't know where else i can ask

for windows or linux? i haven't made it portable for windows.
